// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Dress.proto

package com.qingcity.proto;

public final class DressMessage {
  private DressMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2S_ChangeDressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 clothes = 1;
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    boolean hasClothes();
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    int getClothes();

    // optional int32 pants = 2;
    /**
     * <code>optional int32 pants = 2;</code>
     */
    boolean hasPants();
    /**
     * <code>optional int32 pants = 2;</code>
     */
    int getPants();

    // optional int32 shoes = 3;
    /**
     * <code>optional int32 shoes = 3;</code>
     */
    boolean hasShoes();
    /**
     * <code>optional int32 shoes = 3;</code>
     */
    int getShoes();
  }
  /**
   * Protobuf type {@code C2S_ChangeDress}
   */
  public static final class C2S_ChangeDress extends
      com.google.protobuf.GeneratedMessage
      implements C2S_ChangeDressOrBuilder {
    // Use C2S_ChangeDress.newBuilder() to construct.
    private C2S_ChangeDress(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2S_ChangeDress(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2S_ChangeDress defaultInstance;
    public static C2S_ChangeDress getDefaultInstance() {
      return defaultInstance;
    }

    public C2S_ChangeDress getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_ChangeDress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clothes_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pants_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              shoes_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.DressMessage.internal_static_C2S_ChangeDress_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.DressMessage.internal_static_C2S_ChangeDress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.DressMessage.C2S_ChangeDress.class, com.qingcity.proto.DressMessage.C2S_ChangeDress.Builder.class);
    }

    public static com.google.protobuf.Parser<C2S_ChangeDress> PARSER =
        new com.google.protobuf.AbstractParser<C2S_ChangeDress>() {
      public C2S_ChangeDress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_ChangeDress(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_ChangeDress> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 clothes = 1;
    public static final int CLOTHES_FIELD_NUMBER = 1;
    private int clothes_;
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    public boolean hasClothes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    public int getClothes() {
      return clothes_;
    }

    // optional int32 pants = 2;
    public static final int PANTS_FIELD_NUMBER = 2;
    private int pants_;
    /**
     * <code>optional int32 pants = 2;</code>
     */
    public boolean hasPants() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 pants = 2;</code>
     */
    public int getPants() {
      return pants_;
    }

    // optional int32 shoes = 3;
    public static final int SHOES_FIELD_NUMBER = 3;
    private int shoes_;
    /**
     * <code>optional int32 shoes = 3;</code>
     */
    public boolean hasShoes() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 shoes = 3;</code>
     */
    public int getShoes() {
      return shoes_;
    }

    private void initFields() {
      clothes_ = 0;
      pants_ = 0;
      shoes_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, clothes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pants_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, shoes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clothes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pants_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, shoes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.DressMessage.C2S_ChangeDress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.DressMessage.C2S_ChangeDress prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_ChangeDress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.DressMessage.C2S_ChangeDressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.DressMessage.internal_static_C2S_ChangeDress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.DressMessage.internal_static_C2S_ChangeDress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.DressMessage.C2S_ChangeDress.class, com.qingcity.proto.DressMessage.C2S_ChangeDress.Builder.class);
      }

      // Construct using com.qingcity.proto.DressMessage.C2S_ChangeDress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clothes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pants_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        shoes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.DressMessage.internal_static_C2S_ChangeDress_descriptor;
      }

      public com.qingcity.proto.DressMessage.C2S_ChangeDress getDefaultInstanceForType() {
        return com.qingcity.proto.DressMessage.C2S_ChangeDress.getDefaultInstance();
      }

      public com.qingcity.proto.DressMessage.C2S_ChangeDress build() {
        com.qingcity.proto.DressMessage.C2S_ChangeDress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.DressMessage.C2S_ChangeDress buildPartial() {
        com.qingcity.proto.DressMessage.C2S_ChangeDress result = new com.qingcity.proto.DressMessage.C2S_ChangeDress(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clothes_ = clothes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pants_ = pants_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.shoes_ = shoes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.DressMessage.C2S_ChangeDress) {
          return mergeFrom((com.qingcity.proto.DressMessage.C2S_ChangeDress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.DressMessage.C2S_ChangeDress other) {
        if (other == com.qingcity.proto.DressMessage.C2S_ChangeDress.getDefaultInstance()) return this;
        if (other.hasClothes()) {
          setClothes(other.getClothes());
        }
        if (other.hasPants()) {
          setPants(other.getPants());
        }
        if (other.hasShoes()) {
          setShoes(other.getShoes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.DressMessage.C2S_ChangeDress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.DressMessage.C2S_ChangeDress) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 clothes = 1;
      private int clothes_ ;
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public boolean hasClothes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public int getClothes() {
        return clothes_;
      }
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public Builder setClothes(int value) {
        bitField0_ |= 0x00000001;
        clothes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public Builder clearClothes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clothes_ = 0;
        onChanged();
        return this;
      }

      // optional int32 pants = 2;
      private int pants_ ;
      /**
       * <code>optional int32 pants = 2;</code>
       */
      public boolean hasPants() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 pants = 2;</code>
       */
      public int getPants() {
        return pants_;
      }
      /**
       * <code>optional int32 pants = 2;</code>
       */
      public Builder setPants(int value) {
        bitField0_ |= 0x00000002;
        pants_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pants = 2;</code>
       */
      public Builder clearPants() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pants_ = 0;
        onChanged();
        return this;
      }

      // optional int32 shoes = 3;
      private int shoes_ ;
      /**
       * <code>optional int32 shoes = 3;</code>
       */
      public boolean hasShoes() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 shoes = 3;</code>
       */
      public int getShoes() {
        return shoes_;
      }
      /**
       * <code>optional int32 shoes = 3;</code>
       */
      public Builder setShoes(int value) {
        bitField0_ |= 0x00000004;
        shoes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shoes = 3;</code>
       */
      public Builder clearShoes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        shoes_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:C2S_ChangeDress)
    }

    static {
      defaultInstance = new C2S_ChangeDress(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:C2S_ChangeDress)
  }

  public interface C2S_GetDressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code C2S_GetDress}
   */
  public static final class C2S_GetDress extends
      com.google.protobuf.GeneratedMessage
      implements C2S_GetDressOrBuilder {
    // Use C2S_GetDress.newBuilder() to construct.
    private C2S_GetDress(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2S_GetDress(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2S_GetDress defaultInstance;
    public static C2S_GetDress getDefaultInstance() {
      return defaultInstance;
    }

    public C2S_GetDress getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_GetDress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.DressMessage.internal_static_C2S_GetDress_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.DressMessage.internal_static_C2S_GetDress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.DressMessage.C2S_GetDress.class, com.qingcity.proto.DressMessage.C2S_GetDress.Builder.class);
    }

    public static com.google.protobuf.Parser<C2S_GetDress> PARSER =
        new com.google.protobuf.AbstractParser<C2S_GetDress>() {
      public C2S_GetDress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2S_GetDress(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_GetDress> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.DressMessage.C2S_GetDress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.DressMessage.C2S_GetDress prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_GetDress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.DressMessage.C2S_GetDressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.DressMessage.internal_static_C2S_GetDress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.DressMessage.internal_static_C2S_GetDress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.DressMessage.C2S_GetDress.class, com.qingcity.proto.DressMessage.C2S_GetDress.Builder.class);
      }

      // Construct using com.qingcity.proto.DressMessage.C2S_GetDress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.DressMessage.internal_static_C2S_GetDress_descriptor;
      }

      public com.qingcity.proto.DressMessage.C2S_GetDress getDefaultInstanceForType() {
        return com.qingcity.proto.DressMessage.C2S_GetDress.getDefaultInstance();
      }

      public com.qingcity.proto.DressMessage.C2S_GetDress build() {
        com.qingcity.proto.DressMessage.C2S_GetDress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.DressMessage.C2S_GetDress buildPartial() {
        com.qingcity.proto.DressMessage.C2S_GetDress result = new com.qingcity.proto.DressMessage.C2S_GetDress(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.DressMessage.C2S_GetDress) {
          return mergeFrom((com.qingcity.proto.DressMessage.C2S_GetDress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.DressMessage.C2S_GetDress other) {
        if (other == com.qingcity.proto.DressMessage.C2S_GetDress.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.DressMessage.C2S_GetDress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.DressMessage.C2S_GetDress) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:C2S_GetDress)
    }

    static {
      defaultInstance = new C2S_GetDress(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:C2S_GetDress)
  }

  public interface S2C_DressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 clothes = 1;
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    boolean hasClothes();
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    int getClothes();

    // optional int32 clothesLevel = 2;
    /**
     * <code>optional int32 clothesLevel = 2;</code>
     */
    boolean hasClothesLevel();
    /**
     * <code>optional int32 clothesLevel = 2;</code>
     */
    int getClothesLevel();

    // optional int32 pants = 3;
    /**
     * <code>optional int32 pants = 3;</code>
     */
    boolean hasPants();
    /**
     * <code>optional int32 pants = 3;</code>
     */
    int getPants();

    // optional int32 pantsLevel = 4;
    /**
     * <code>optional int32 pantsLevel = 4;</code>
     */
    boolean hasPantsLevel();
    /**
     * <code>optional int32 pantsLevel = 4;</code>
     */
    int getPantsLevel();

    // optional int32 shoes = 5;
    /**
     * <code>optional int32 shoes = 5;</code>
     */
    boolean hasShoes();
    /**
     * <code>optional int32 shoes = 5;</code>
     */
    int getShoes();

    // optional int32 shoesLevel = 6;
    /**
     * <code>optional int32 shoesLevel = 6;</code>
     */
    boolean hasShoesLevel();
    /**
     * <code>optional int32 shoesLevel = 6;</code>
     */
    int getShoesLevel();
  }
  /**
   * Protobuf type {@code S2C_Dress}
   */
  public static final class S2C_Dress extends
      com.google.protobuf.GeneratedMessage
      implements S2C_DressOrBuilder {
    // Use S2C_Dress.newBuilder() to construct.
    private S2C_Dress(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2C_Dress(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2C_Dress defaultInstance;
    public static S2C_Dress getDefaultInstance() {
      return defaultInstance;
    }

    public S2C_Dress getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_Dress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clothes_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clothesLevel_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pants_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pantsLevel_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              shoes_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              shoesLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.DressMessage.internal_static_S2C_Dress_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.DressMessage.internal_static_S2C_Dress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.DressMessage.S2C_Dress.class, com.qingcity.proto.DressMessage.S2C_Dress.Builder.class);
    }

    public static com.google.protobuf.Parser<S2C_Dress> PARSER =
        new com.google.protobuf.AbstractParser<S2C_Dress>() {
      public S2C_Dress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_Dress(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_Dress> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 clothes = 1;
    public static final int CLOTHES_FIELD_NUMBER = 1;
    private int clothes_;
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    public boolean hasClothes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 clothes = 1;</code>
     */
    public int getClothes() {
      return clothes_;
    }

    // optional int32 clothesLevel = 2;
    public static final int CLOTHESLEVEL_FIELD_NUMBER = 2;
    private int clothesLevel_;
    /**
     * <code>optional int32 clothesLevel = 2;</code>
     */
    public boolean hasClothesLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 clothesLevel = 2;</code>
     */
    public int getClothesLevel() {
      return clothesLevel_;
    }

    // optional int32 pants = 3;
    public static final int PANTS_FIELD_NUMBER = 3;
    private int pants_;
    /**
     * <code>optional int32 pants = 3;</code>
     */
    public boolean hasPants() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 pants = 3;</code>
     */
    public int getPants() {
      return pants_;
    }

    // optional int32 pantsLevel = 4;
    public static final int PANTSLEVEL_FIELD_NUMBER = 4;
    private int pantsLevel_;
    /**
     * <code>optional int32 pantsLevel = 4;</code>
     */
    public boolean hasPantsLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 pantsLevel = 4;</code>
     */
    public int getPantsLevel() {
      return pantsLevel_;
    }

    // optional int32 shoes = 5;
    public static final int SHOES_FIELD_NUMBER = 5;
    private int shoes_;
    /**
     * <code>optional int32 shoes = 5;</code>
     */
    public boolean hasShoes() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 shoes = 5;</code>
     */
    public int getShoes() {
      return shoes_;
    }

    // optional int32 shoesLevel = 6;
    public static final int SHOESLEVEL_FIELD_NUMBER = 6;
    private int shoesLevel_;
    /**
     * <code>optional int32 shoesLevel = 6;</code>
     */
    public boolean hasShoesLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 shoesLevel = 6;</code>
     */
    public int getShoesLevel() {
      return shoesLevel_;
    }

    private void initFields() {
      clothes_ = 0;
      clothesLevel_ = 0;
      pants_ = 0;
      pantsLevel_ = 0;
      shoes_ = 0;
      shoesLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, clothes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clothesLevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pants_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pantsLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, shoes_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, shoesLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clothes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clothesLevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pants_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pantsLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, shoes_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, shoesLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.DressMessage.S2C_Dress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.DressMessage.S2C_Dress prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code S2C_Dress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.DressMessage.S2C_DressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.DressMessage.internal_static_S2C_Dress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.DressMessage.internal_static_S2C_Dress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.DressMessage.S2C_Dress.class, com.qingcity.proto.DressMessage.S2C_Dress.Builder.class);
      }

      // Construct using com.qingcity.proto.DressMessage.S2C_Dress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clothes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        clothesLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pants_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        pantsLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        shoes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        shoesLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.DressMessage.internal_static_S2C_Dress_descriptor;
      }

      public com.qingcity.proto.DressMessage.S2C_Dress getDefaultInstanceForType() {
        return com.qingcity.proto.DressMessage.S2C_Dress.getDefaultInstance();
      }

      public com.qingcity.proto.DressMessage.S2C_Dress build() {
        com.qingcity.proto.DressMessage.S2C_Dress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.DressMessage.S2C_Dress buildPartial() {
        com.qingcity.proto.DressMessage.S2C_Dress result = new com.qingcity.proto.DressMessage.S2C_Dress(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clothes_ = clothes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clothesLevel_ = clothesLevel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pants_ = pants_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pantsLevel_ = pantsLevel_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.shoes_ = shoes_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.shoesLevel_ = shoesLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.DressMessage.S2C_Dress) {
          return mergeFrom((com.qingcity.proto.DressMessage.S2C_Dress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.DressMessage.S2C_Dress other) {
        if (other == com.qingcity.proto.DressMessage.S2C_Dress.getDefaultInstance()) return this;
        if (other.hasClothes()) {
          setClothes(other.getClothes());
        }
        if (other.hasClothesLevel()) {
          setClothesLevel(other.getClothesLevel());
        }
        if (other.hasPants()) {
          setPants(other.getPants());
        }
        if (other.hasPantsLevel()) {
          setPantsLevel(other.getPantsLevel());
        }
        if (other.hasShoes()) {
          setShoes(other.getShoes());
        }
        if (other.hasShoesLevel()) {
          setShoesLevel(other.getShoesLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.DressMessage.S2C_Dress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.DressMessage.S2C_Dress) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 clothes = 1;
      private int clothes_ ;
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public boolean hasClothes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public int getClothes() {
        return clothes_;
      }
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public Builder setClothes(int value) {
        bitField0_ |= 0x00000001;
        clothes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clothes = 1;</code>
       */
      public Builder clearClothes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clothes_ = 0;
        onChanged();
        return this;
      }

      // optional int32 clothesLevel = 2;
      private int clothesLevel_ ;
      /**
       * <code>optional int32 clothesLevel = 2;</code>
       */
      public boolean hasClothesLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 clothesLevel = 2;</code>
       */
      public int getClothesLevel() {
        return clothesLevel_;
      }
      /**
       * <code>optional int32 clothesLevel = 2;</code>
       */
      public Builder setClothesLevel(int value) {
        bitField0_ |= 0x00000002;
        clothesLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clothesLevel = 2;</code>
       */
      public Builder clearClothesLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clothesLevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 pants = 3;
      private int pants_ ;
      /**
       * <code>optional int32 pants = 3;</code>
       */
      public boolean hasPants() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 pants = 3;</code>
       */
      public int getPants() {
        return pants_;
      }
      /**
       * <code>optional int32 pants = 3;</code>
       */
      public Builder setPants(int value) {
        bitField0_ |= 0x00000004;
        pants_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pants = 3;</code>
       */
      public Builder clearPants() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pants_ = 0;
        onChanged();
        return this;
      }

      // optional int32 pantsLevel = 4;
      private int pantsLevel_ ;
      /**
       * <code>optional int32 pantsLevel = 4;</code>
       */
      public boolean hasPantsLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 pantsLevel = 4;</code>
       */
      public int getPantsLevel() {
        return pantsLevel_;
      }
      /**
       * <code>optional int32 pantsLevel = 4;</code>
       */
      public Builder setPantsLevel(int value) {
        bitField0_ |= 0x00000008;
        pantsLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pantsLevel = 4;</code>
       */
      public Builder clearPantsLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pantsLevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 shoes = 5;
      private int shoes_ ;
      /**
       * <code>optional int32 shoes = 5;</code>
       */
      public boolean hasShoes() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 shoes = 5;</code>
       */
      public int getShoes() {
        return shoes_;
      }
      /**
       * <code>optional int32 shoes = 5;</code>
       */
      public Builder setShoes(int value) {
        bitField0_ |= 0x00000010;
        shoes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shoes = 5;</code>
       */
      public Builder clearShoes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        shoes_ = 0;
        onChanged();
        return this;
      }

      // optional int32 shoesLevel = 6;
      private int shoesLevel_ ;
      /**
       * <code>optional int32 shoesLevel = 6;</code>
       */
      public boolean hasShoesLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 shoesLevel = 6;</code>
       */
      public int getShoesLevel() {
        return shoesLevel_;
      }
      /**
       * <code>optional int32 shoesLevel = 6;</code>
       */
      public Builder setShoesLevel(int value) {
        bitField0_ |= 0x00000020;
        shoesLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shoesLevel = 6;</code>
       */
      public Builder clearShoesLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        shoesLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:S2C_Dress)
    }

    static {
      defaultInstance = new S2C_Dress(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:S2C_Dress)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_ChangeDress_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C2S_ChangeDress_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_GetDress_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_C2S_GetDress_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_S2C_Dress_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_S2C_Dress_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Dress.proto\"@\n\017C2S_ChangeDress\022\017\n\007clot" +
      "hes\030\001 \001(\005\022\r\n\005pants\030\002 \001(\005\022\r\n\005shoes\030\003 \001(\005\"" +
      "\016\n\014C2S_GetDress\"x\n\tS2C_Dress\022\017\n\007clothes\030" +
      "\001 \001(\005\022\024\n\014clothesLevel\030\002 \001(\005\022\r\n\005pants\030\003 \001" +
      "(\005\022\022\n\npantsLevel\030\004 \001(\005\022\r\n\005shoes\030\005 \001(\005\022\022\n" +
      "\nshoesLevel\030\006 \001(\005B\"\n\022com.qingcity.protoB" +
      "\014DressMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_C2S_ChangeDress_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_C2S_ChangeDress_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C2S_ChangeDress_descriptor,
              new java.lang.String[] { "Clothes", "Pants", "Shoes", });
          internal_static_C2S_GetDress_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_C2S_GetDress_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_C2S_GetDress_descriptor,
              new java.lang.String[] { });
          internal_static_S2C_Dress_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_S2C_Dress_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_S2C_Dress_descriptor,
              new java.lang.String[] { "Clothes", "ClothesLevel", "Pants", "PantsLevel", "Shoes", "ShoesLevel", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
