// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gain.proto

package com.qingcity.proto;

public final class GainProto {
  private GainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface S2C_GainOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string gain = 1;
    /**
     * <code>optional string gain = 1;</code>
     */
    boolean hasGain();
    /**
     * <code>optional string gain = 1;</code>
     */
    java.lang.String getGain();
    /**
     * <code>optional string gain = 1;</code>
     */
    com.google.protobuf.ByteString
        getGainBytes();
  }
  /**
   * Protobuf type {@code S2C_Gain}
   */
  public static final class S2C_Gain extends
      com.google.protobuf.GeneratedMessage
      implements S2C_GainOrBuilder {
    // Use S2C_Gain.newBuilder() to construct.
    private S2C_Gain(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2C_Gain(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2C_Gain defaultInstance;
    public static S2C_Gain getDefaultInstance() {
      return defaultInstance;
    }

    public S2C_Gain getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_Gain(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              gain_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcity.proto.GainProto.internal_static_S2C_Gain_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcity.proto.GainProto.internal_static_S2C_Gain_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcity.proto.GainProto.S2C_Gain.class, com.qingcity.proto.GainProto.S2C_Gain.Builder.class);
    }

    public static com.google.protobuf.Parser<S2C_Gain> PARSER =
        new com.google.protobuf.AbstractParser<S2C_Gain>() {
      public S2C_Gain parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_Gain(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_Gain> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string gain = 1;
    public static final int GAIN_FIELD_NUMBER = 1;
    private java.lang.Object gain_;
    /**
     * <code>optional string gain = 1;</code>
     */
    public boolean hasGain() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string gain = 1;</code>
     */
    public java.lang.String getGain() {
      java.lang.Object ref = gain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gain = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGainBytes() {
      java.lang.Object ref = gain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      gain_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGainBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGainBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcity.proto.GainProto.S2C_Gain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcity.proto.GainProto.S2C_Gain prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code S2C_Gain}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcity.proto.GainProto.S2C_GainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcity.proto.GainProto.internal_static_S2C_Gain_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcity.proto.GainProto.internal_static_S2C_Gain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcity.proto.GainProto.S2C_Gain.class, com.qingcity.proto.GainProto.S2C_Gain.Builder.class);
      }

      // Construct using com.qingcity.proto.GainProto.S2C_Gain.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gain_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcity.proto.GainProto.internal_static_S2C_Gain_descriptor;
      }

      public com.qingcity.proto.GainProto.S2C_Gain getDefaultInstanceForType() {
        return com.qingcity.proto.GainProto.S2C_Gain.getDefaultInstance();
      }

      public com.qingcity.proto.GainProto.S2C_Gain build() {
        com.qingcity.proto.GainProto.S2C_Gain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcity.proto.GainProto.S2C_Gain buildPartial() {
        com.qingcity.proto.GainProto.S2C_Gain result = new com.qingcity.proto.GainProto.S2C_Gain(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gain_ = gain_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcity.proto.GainProto.S2C_Gain) {
          return mergeFrom((com.qingcity.proto.GainProto.S2C_Gain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcity.proto.GainProto.S2C_Gain other) {
        if (other == com.qingcity.proto.GainProto.S2C_Gain.getDefaultInstance()) return this;
        if (other.hasGain()) {
          bitField0_ |= 0x00000001;
          gain_ = other.gain_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcity.proto.GainProto.S2C_Gain parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcity.proto.GainProto.S2C_Gain) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string gain = 1;
      private java.lang.Object gain_ = "";
      /**
       * <code>optional string gain = 1;</code>
       */
      public boolean hasGain() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string gain = 1;</code>
       */
      public java.lang.String getGain() {
        java.lang.Object ref = gain_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          gain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gain = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGainBytes() {
        java.lang.Object ref = gain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gain = 1;</code>
       */
      public Builder setGain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gain = 1;</code>
       */
      public Builder clearGain() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gain_ = getDefaultInstance().getGain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gain = 1;</code>
       */
      public Builder setGainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gain_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:S2C_Gain)
    }

    static {
      defaultInstance = new S2C_Gain(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:S2C_Gain)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_S2C_Gain_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_S2C_Gain_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngain.proto\"\030\n\010S2C_Gain\022\014\n\004gain\030\001 \001(\tB\037" +
      "\n\022com.qingcity.protoB\tGainProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_S2C_Gain_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_S2C_Gain_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_S2C_Gain_descriptor,
              new java.lang.String[] { "Gain", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
